import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./styles.css";
import type{Instance,VersionSummary}from"../shared/types";
import{NAV_ITEMS}from"../shared/constants";

const nav=[...NAV_ITEMS,"Mods","Worlds","Java","Diagnostics"];
function App(){
 const[page,setPage]=useState("Home"),[state,setState]=useState<any>(),[versions,setVersions]=useState<VersionSummary[]>([]),[hardware,setHardware]=useState<any>(),[selected,setSelected]=useState<string>(),[create,setCreate]=useState(false),[launch,setLaunch]=useState<any>({state:"IDLE"}),[toast,setToast]=useState(""),[logs,setLogs]=useState<string[]>([]);
 const refresh=()=>window.skybounders.state().then((s:any)=>{setState(s);if(!selected)setSelected(s.settings.defaultInstanceId||s.instances[0]?.id)});
 useEffect(()=>{refresh();window.skybounders.hardware.get().then(setHardware);const u1=window.skybounders.on("game:state",setLaunch),u2=window.skybounders.on("game:log",(x:any)=>setLogs(l=>[...l,String(x)].slice(-120));return()=>{u1();u2()}},[]);
 useEffect(()=>{if(page==="Versions")window.skybounders.versions.list().then((x:any)=>setVersions(x.versions||[])).catch((e:any)=>setToast(e.message))},[page]);
 useEffect(()=>{const f=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();document.getElementById("global-search")?.focus()}};addEventListener("keydown",f);return()=>removeEventListener("keydown",f)},[]);
 const current=(state?.instances||[]).find((i:any)=>i.id===selected)||(state?.instances||[])[0];
 const notify=(e:any)=>{setToast(e?.message||String(e));setTimeout(()=>setToast(""),3500)};
 const play=async()=>{if(!current)return notify(new Error("Create an instance first."));try{await window.skybounders.game.launch(current.id)}catch(e){notify(e)}};
 return <div className="app"><header className="topbar"><div className="brand"><b>S</b><span>SKYBOUNDERS<small>LAUNCHER</small></span></div><div className="title">{page}</div><div className="account">{state?.accounts?.[0]?`● ${state.accounts[0].displayName}`:"No account"}</div><button onClick={window.skybounders.window.minimize}>—</button><button onClick={window.skybounders.window.toggleMaximize}>□</button><button onClick={window.skybounders.window.close}>×</button></header>
 <div className="body"><aside><div className="nav-scroll">{nav.map(n=><button key={n} className={page===n?"active":""} onClick={()=>setPage(n)}>{n}</button>)}</div><div className="aside-bottom">{hardware?`${hardware.cpu} · ${Math.round(hardware.ramMb/1024)} GB RAM`:"Detecting hardware…"}<span>v{state?"0.1":"—"}</span></div></aside>
 <main><div className="search"><input id="global-search" placeholder="Search Skybounders…  Ctrl K" onKeyDown={e=>{if(e.key==="Enter"){const q=(e.target as HTMLInputElement).value.toLowerCase();const n=nav.find(x=>x.toLowerCase().includes(q));if(n)setPage(n)}}}/></div>
 {page==="Home"&&<Home current={current} state={state} launch={launch} play={play} create={()=>setCreate(true)} select={setSelected} refresh={refresh}/>} 
 {page==="Instances"&&<Instances state={state} select={setSelected} create={()=>setCreate(true)} refresh={refresh} notify={notify}/>} 
 {page==="Versions"&&<Versions versions={versions} create={()=>setCreate(true)}/>} 
 {page==="Discover"&&<Discover current={current} notify={notify}/>} 
 {page==="Modpacks"&&<Discover current={current} type="modpack" notify={notify}/>} 
 {page==="Mods"&&<Mods current={current} notify={notify}/>} 
 {page==="Worlds"&&<Worlds current={current} state={state} notify={notify} refresh={refresh}/>} 
 {page==="Downloads"&&<Downloads state={state}/>} 
 {page==="Accounts"&&<Accounts state={state} refresh={refresh} notify={notify}/>} 
 {page==="Java"&&<Java notify={notify}/>} 
 {page==="Diagnostics"&&<Diagnostics current={current} notify={notify}/>} 
 {page==="Settings"&&<Settings state={state} hardware={hardware} refresh={refresh}/>} 
 </main></div>{create&&<Create versions={versions} close={()=>setCreate(false)} done={async(v,n,l)=>{const safe=n.trim().replace(/[^a-z0-9-_ ]/gi,"-")||"Survival";const i:Instance={id:crypto.randomUUID(),name:safe,platform:"java",minecraftVersion:v,loader:l,directory:`${state.settings.gameDirectory}/instances/${safe}`,memoryMb:state.settings.defaultMemoryMb,jvmArgs:"",createdAt:new Date().toISOString()};try{await window.skybounders.instances.save(i);await refresh();setSelected(i.id);setCreate(false);notify(new Error("Instance created"))}catch(e){notify(e)}}}/>} {launch.state==="DOWNLOADING"&&<div className="bottom"><b>{launch.label||"Downloading"}</b><div><span style={{width:`${launch.progress||0}%`}}/></div><small>{launch.progress||0}%</small></div>}{logs.length>0&&launch.state==="RUNNING"&&<div className="log-dock"><div className="log-head"><b>LIVE CONSOLE</b><span>{logs.length} lines</span></div><pre>{logs.slice(-18).join("")}</pre></div>}{toast&&<div className="toast">{toast}</div>}</div>
}
function Home({current,state,launch,play,create,select}:any){return <><section className="hero"><div><small>SELECTED INSTANCE</small><h1>{current?.name||"Your sky is empty."}</h1><p>{current?`${current.minecraftVersion} · ${current.loader} · ${current.memoryMb} MB`:"Create a dedicated, isolated Minecraft instance."}</p><button className="play" onClick={play}>{launch.state==="RUNNING"?"RUNNING":launch.state==="STARTING"?"STARTING":"PLAY"}</button><button className="secondary" onClick={create}>New Instance</button></div><div className="hero-meta"><span>{state?.instances?.length||0}<small>INSTANCES</small></span><span>{state?.downloads?.filter((x:any)=>x.status==="completed").length||0}<small>COMPLETED</small></span></div></section><div className="section-head"><h2>Recent instances</h2><span>Double-click ready</span></div><div className="cards">{(state?.instances||[]).map((i:Instance)=><button className="card" key={i.id} onClick={()=>select(i.id)}><b>{i.favorite?"★ ":""}{i.name}</b><span>{i.minecraftVersion} · {i.loader}</span><small>{i.lastPlayedAt?`Played ${new Date(i.lastPlayedAt).toLocaleDateString()}`:"Never launched"}</small></button>)}{!state?.instances?.length&&<div className="empty"><b>No instances yet</b><span>Create your first instance to start downloading Minecraft.</span><button className="secondary" onClick={create}>Create instance</button></div>}</div></>}
function Instances({state,select,create,refresh,notify}:any){return <><div className="section-head"><div><h1>Instances</h1><p>Separate game directories, memory limits, accounts and runtime choices.</p></div><button className="primary" onClick={create}>＋ New Instance</button></div><div className="grid-3">{(state?.instances||[]).map((i:Instance)=><div className="instance-card" key={i.id}><div className="instance-icon">{i.loader[0].toUpperCase()}</div><div><b>{i.name}</b><span>{i.minecraftVersion} · {i.loader}</span><small>{Math.round(i.memoryMb/1024*10)/10} GB RAM</small></div><div className="instance-actions"><button className="secondary" onClick={()=>select(i.id)}>Select</button><button className="ghost" onClick={()=>window.skybounders.instances.open(i.id)}>Folder</button><button className="ghost" onClick={async()=>{try{await window.skybounders.instances.duplicate(i.id,`${i.name} Copy`);await refresh()}catch(e){notify(e)}}}>Duplicate</button><button className="danger" onClick={async()=>{try{await window.skybounders.instances.delete(i.id);await refresh()}catch(e){notify(e)}}}>Delete</button></div></div>)}</div></>}
function Versions({versions,create}:any){return <><h1>Minecraft Versions</h1><p>Live Mojang launcher metadata. Release/snapshot filtering stays server-authoritative.</p><div className="list">{versions.slice(0,120).map((v:any)=><div className="row" key={v.id}><div><b>{v.id}</b><span>{v.type}</span></div><span>{new Date(v.releaseTime).toLocaleDateString()}</span><button className="secondary" onClick={create}>Use</button></div>)}</div></>}
function ProviderTabs({provider,setProvider}:{provider:string;setProvider:(x:string)=>void}){return <div className="tabs"><button className={provider==="modrinth"?"active":""} onClick={()=>setProvider("modrinth")}>Modrinth</button><button className={provider==="curseforge"?"active":""} onClick={()=>setProvider("curseforge")}>CurseForge</button></div>}
function Discover({current,type="mod",notify}:any){const[q,setQ]=useState("sodium"),[provider,setProvider]=useState("modrinth"),[results,setResults]=useState<any[]>([]),[busy,setBusy]=useState(false);const search=async()=>{setBusy(true);try{setResults(provider==="modrinth"?await window.skybounders.modrinth.search(q,type):await window.skybounders.curseforge.search(q,current?.minecraftVersion))}catch(e){notify(e)}finally{setBusy(false)}};return <><div className="section-head"><div><h1>{type==="modpack"?"Modpacks":"Discover"}</h1><p>Search both supported catalogs without embedding their websites.</p></div></div><ProviderTabs provider={provider} setProvider={setProvider}/><div className="searchbar"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder={`Search ${type}s…`}/><button className="primary" onClick={search}>{busy?"Searching…":"Search"}</button></div><div className="projects">{results.map((r:any)=><div className="project" key={r.project_id||r.id}><div className="project-top">{r.icon_url&&<img src={r.icon_url}/>}<div><b>{r.title||r.name}</b><span>{r.author||r.authors?.[0]?.name||"Unknown author"} · {(r.downloads||r.downloadCount||0).toLocaleString()} downloads</span></div></div><p>{r.description||r.summary||"No description."}</p>{current&&type==="mod"&&<button className="secondary" onClick={async()=>{try{if(provider==="modrinth"){await window.skybounders.mods.installModrinth(current.id,r.project_id)}else{await window.skybounders.mods.installCurseForge(current.id,String(r.id))}notify(new Error("Installed successfully"))}catch(e){notify(e)}}}>Install to {current.name}</button>}</div>)}</div></>}
function Mods({current,notify}:any){const[items,setItems]=useState<any[]>([]),[busy,setBusy]=useState(false);const load=()=>current&&window.skybounders.mods.installed(current.id).then(setItems);useEffect(()=>{load()},[current?.id]);return <><div className="section-head"><div><h1>Installed Mods</h1><p>{current?current.name:"Select an instance first."}</p></div><button className="secondary" disabled={!current} onClick={load}>Refresh</button></div>{!current?<div className="empty"><b>No instance selected</b><span>Select an instance to manage its mods.</span></div>:<div className="list">{items.map(x=><div className="row" key={x.name}><div><b>{x.name}</b><span>{Math.round(x.sizeBytes/1024)} KB</span></div><button className="danger" onClick={async()=>{try{setBusy(true);await window.skybounders.mods.remove(current.id,x.name);await load()}catch(e){notify(e)}finally{setBusy(false)}}}>{busy?"…":"Remove"}</button></div>)}{!items.length&&<div className="empty"><b>No .jar mods installed</b><span>Use Discover to find a compatible mod and install it.</span></div>}</div>}</>}
function Worlds({current,state,notify,refresh}:any){const[worlds,setWorlds]=useState<any[]>([]);const load=()=>current&&window.skybounders.worlds.list(current.id).then(setWorlds);useEffect(()=>{load()},[current?.id]);return <><div className="section-head"><div><h1>Worlds</h1><p>Browse, back up and remove worlds without touching other instances.</p></div><button className="secondary" disabled={!current} onClick={load}>Refresh</button></div>{current?<div className="list">{worlds.map(w=><div className="row" key={w.name}><div><b>{w.name}</b><span>{Math.round(w.sizeBytes/1048576*10)/10} MB · {new Date(w.modifiedAt).toLocaleString()}</span></div><div><button className="secondary" onClick={()=>window.skybounders.path.open(w.path)}>Open</button><button className="secondary" onClick={async()=>{try{await window.skybounders.worlds.backup(current.id,w.name);await refresh();notify(new Error("Backup created"))}catch(e){notify(e)}}}>Backup</button><button className="danger" onClick={async()=>{try{await window.skybounders.worlds.delete(current.id,w.name);await load()}catch(e){notify(e)}}}>Delete</button></div></div>)}{!worlds.length&&<div className="empty"><b>No worlds detected</b><span>Worlds appear here after Minecraft creates the saves folder.</span></div>}</div>:<div className="empty"><b>No instance selected</b><span>Select an instance first.</span></div>}</>}
function Downloads({state}:any){const items=state?.downloads||[];return <><div className="section-head"><div><h1>Downloads</h1><p>Every tracked transfer, speed and final state.</p></div></div><div className="list">{items.slice().reverse().map((d:any)=><div className="download-row" key={d.id}><div><b>{d.label}</b><span>{d.source}</span></div><div className="download-main"><div className="mini-progress"><span style={{width:`${d.size?Math.min(100,d.downloaded/d.size*100):d.status==="completed"?100:0}%`}}/></div><small>{d.status}{d.size?` · ${Math.round(d.downloaded/1048576*10)/10}/${Math.round(d.size/1048576*10)/10} MB`:""}</small></div>{d.status==="active"&&<button className="danger" onClick={()=>window.skybounders.downloads.cancel(d.id)}>Cancel</button>}</div>)}{!items.length&&<div className="empty"><b>Nothing downloaded yet</b><span>Game files and mods will appear here.</span></div>}</div></>}
function Accounts({state,refresh,notify}:any){return <><h1>Accounts</h1><p>Microsoft authentication uses the device-code flow; no password is stored by the launcher.</p><button className="primary" onClick={async()=>{try{const a=await window.skybounders.auth.microsoft();await window.skybounders.accounts.save(a);await refresh();notify(new Error(`Signed in as ${a.displayName}`))}catch(e){notify(e)}}}>＋ Add Microsoft Account</button>{(state?.accounts||[]).map((a:any)=><div className="account-card" key={a.id}><div><b>{a.displayName}</b><span>{a.provider} · {a.status}{a.uuid?` · ${a.uuid.slice(0,8)}…`:""}</span></div><button className="danger" onClick={async()=>{await window.skybounders.accounts.remove(a.id);await refresh()}}>Remove</button></div>)}</>}
function Java({notify}:any){const[items,setItems]=useState<any[]>([]);const scan=async()=>{try{setItems(await window.skybounders.java.scan())}catch(e){notify(e)}};useEffect(()=>{scan()},[]);return <><div className="section-head"><div><h1>Java Runtimes</h1><p>Detected JDK/JRE installations available to Minecraft.</p></div><button className="primary" onClick={scan}>Scan</button></div><div className="list">{items.map((j:any)=><div className="row" key={j.path}><div><b>Java {j.major}</b><span>{j.version} · {j.vendor||"Unknown vendor"}</span></div><code>{j.path}</code></div>)}{!items.length&&<div className="empty"><b>No Java runtimes detected</b><span>Install a supported Java runtime or add a custom search path in Settings.</span></div>}</div></>}
function Diagnostics({current,notify}:any){const[report,setReport]=useState<any>();return <><h1>Diagnostics</h1><p>Generate a portable report for crashes and support without uploading it anywhere.</p><div className="settings"><button className="primary" onClick={async()=>setReport(await window.skybounders.diagnostics.create(current?.id))}>Generate report</button>{report&&<><pre className="report">{JSON.stringify(report,null,2)}</pre><button className="secondary" onClick={async()=>{try{const p=await window.skybounders.diagnostics.save(report);notify(new Error(`Saved to ${p}`))}catch(e){notify(e)}}}>Save JSON</button></>}</div></>}
function Settings({state,hardware,refresh}:any){const s=state?.settings||{};const upd=async(x:any)=>{await window.skybounders.settings.update(x);await refresh()};return <><h1>Settings</h1><div className="settings"><label>Performance<select value={s.performance} onChange={e=>upd({performance:e.target.value})}><option value="potato">Potato</option><option value="balanced">Balanced</option><option value="performance">Performance</option><option value="custom">Custom</option></select></label><label>Default memory <span>{s.defaultMemoryMb} MB</span><input type="range" min="1024" max={Math.max(8192,Math.floor((hardware?.ramMb||8192)*0.75))} step="512" value={s.defaultMemoryMb} onChange={e=>upd({defaultMemoryMb:+e.target.value})}/></label><label>Download concurrency <span>{s.downloadConcurrency}</span><input type="range" min="1" max="8" value={s.downloadConcurrency} onChange={e=>upd({downloadConcurrency:+e.target.value})}/></label><label>Animated background<input type="checkbox" checked={!!s.animatedBackground} onChange={e=>upd({animatedBackground:e.target.checked})}/></label><label>Start at login<input type="checkbox" checked={!!s.startAtLogin} onChange={e=>upd({startAtLogin:e.target.checked})}/></label><label>Close launcher after Play<input type="checkbox" checked={!!s.closeOnLaunch} onChange={e=>upd({closeOnLaunch:e.target.checked})}/></label><label>CurseForge API key<input type="password" value={s.curseforgeApiKey||""} onChange={e=>upd({curseforgeApiKey:e.target.value})} placeholder="Paste your application key"/></label><div className="empty"><b>Game directory</b><span>{s.gameDirectory}</span><button className="secondary" onClick={()=>window.skybounders.path.open(s.gameDirectory)}>Open</button></div></div></>}
function Create({versions,close,done}:any){const[v,setV]=useState(versions[0]?.id||"1.21.8"),[n,setN]=useState("Survival"),[l,setL]=useState("vanilla");return <div className="overlay"><div className="modal"><small>NEW INSTANCE</small><h2>Create your sky</h2><label>Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Version<select value={v} onChange={e=>setV(e.target.value)}>{versions.slice(0,60).map((x:any)=><option key={x.id} value={x.id}>{x.id}</option>)}</select></label><label>Loader<select value={l} onChange={e=>setL(e.target.value)}><option value="vanilla">Vanilla</option><option value="fabric" disabled>Fabric — installer coming</option><option value="forge" disabled>Forge — installer coming</option><option value="neoforge" disabled>NeoForge — installer coming</option><option value="quilt" disabled>Quilt — installer coming</option></select></label><div className="actions"><button className="secondary" onClick={close}>Cancel</button><button className="primary" onClick={()=>done(v,n,l)}>Create</button></div></div></div>}
createRoot(document.getElementById("root")!).render(<App/>);
